name: nutricheck
description: "Nutricheck - Aplikasi Pengecek Zat Aditif Makanan Kemasan"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_center.png
  branding: assets/splash_branding.png
  color_dark: "#ffffff"
  image_dark: assets/splash_center.png
  branding_dark: assets/splash_branding.png
  android_12:
    color: "#ffffff"
    image: assets/splash_center.png
    branding: assets/splash_branding.png
    color_dark: "#ffffff"
    image_dark: assets/splash_center.png
    branding_dark: assets/splash_branding.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
